#!/usr/bin/env node
/**
 * Don Hermes OS — Environment Setup Script
 *
 * Detects the local environment, generates .env files, and configures
 * everything needed to run Don Hermes OS for the first time.
 *
 * Usage:  bun run scripts/setup.mjs
 *         node scripts/setup.mjs
 *         npm run setup
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { randomBytes } from 'crypto';
import { createInterface } from 'readline';
import path from 'path';
import os from 'os';

const ROOT = path.dirname(new URL(import.meta.url).pathname);
const HOME = os.homedir();
const HERMES_DIR = `${HOME}/.hermes`;
const PROFILES_DIR = `${HERMES_DIR}/profiles`;
const LOGS_DIR = `${HOME}/logs`;
const COLORS = {
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
  reset: '\x1b[0m',
};

function log(emoji, msg, color = '') {
  const c = COLORS[color] || '';
  console.log(` ${emoji} ${c}${msg}${COLORS.reset}`);
}

function ask(query) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => rl.question(`\n ❓ ${query}: `, ans => { rl.close(); resolve(ans.trim()); }));
}

// ═══════════════════════════════════════════════════════════
//  DETECTION
// ═══════════════════════════════════════════════════════════

function detectLocalIp() {
  try {
    const out = execSync('hostname -I', { timeout: 2000, encoding: 'utf-8' });
    const ips = out.trim().split(/\s+/).filter(ip => ip.includes('.') && !ip.startsWith('127.'));
    return ips[0] || '127.0.0.1';
  } catch { return '127.0.0.1'; }
}

function detectTool(name, checkCmd) {
  try {
    execSync(checkCmd, { timeout: 2000, stdio: 'ignore' });
    return true;
  } catch { return false; }
}

function detectGpu() {
  try {
    const out = execSync('nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null', { timeout: 3000, encoding: 'utf-8' });
    return out.trim().split('\n').filter(Boolean);
  } catch { return []; }
}

// ═══════════════════════════════════════════════════════════
//  GENERATORS
// ═══════════════════════════════════════════════════════════

function generateProfileEnv(localIp, port, apiKey, corsPorts = ['3001', '3002']) {
  // Generate CORS origins for each port + IP combination
  const ips = [localIp, 'localhost', '127.0.0.1'];
  const corsOrigins = [];
  for (const ip of ips) {
    for (const p of corsPorts) {
      corsOrigins.push(`http://${ip}:${p}`);
    }
  }


  return [
    '# Don Hermes OS — Auto-generated .env',
    '# Generated by scripts/setup.mjs',
    `# Date: ${new Date().toISOString().split('T')[0]}`,
    '',
    '#API SERVER SETTINGS',
    'API_SERVER_ENABLED=true',
    'API_SERVER_HOST=0.0.0.0',
    `API_SERVER_PORT=${port}`,
    `API_SERVER_KEY=${apiKey}`,
    `API_SERVER_CORS_ORIGINS=${corsOrigins}`,
    'API_SERVER_CORS_ALLOWED_HEADERS=*',
    'API_SERVER_CORS_EXPOSE_HEADERS=*',
    '',
    '# GATEWAY',
    'GATEWAY_HOST=127.0.0.1',
    'GATEWAY_PORT=8642',
    'GATEWAY_AUTH=',
    '',
    '# LLM',
    'LLM_MODEL=',
    'DEFAULT_MODEL=',
    'TERMINAL_TIMEOUT=60',
    'TERMINAL_LIFETIME_SECONDS=300',
    'BROWSER_SESSION_TIMEOUT=300',
    'BROWSER_INACTIVITY_TIMEOUT=120',
  ].join('\n') + '\n';
}

function generateApiKey() {
  try {
    return execSync('openssl rand -hex 32', { timeout: 2000, encoding: 'utf-8' }).trim();
  } catch {
    return randomBytes(32).toString('hex');
  }
}

// ═══════════════════════════════════════════════════════════
//  MAIN
// ═══════════════════════════════════════════════════════════

async function main() {
  const startTime = Date.now();
  const ciMode = process.argv.includes('--ci') || process.env.CI === 'true';

  console.log(`\n${COLORS.cyan}╔══════════════════════════════════════════╗${COLORS.reset}`);
  console.log(`${COLORS.cyan}║     Don Hermes OS — Environment Setup   ║${COLORS.reset}`);
  if (ciMode) log('🤖', 'Running in CI/non-interactive mode');
  console.log(`${COLORS.cyan}╚══════════════════════════════════════════╝${COLORS.reset}\n`);

  // ── 1. Detect ──────────────────────────────────────────

  log('🔍', 'Detecting environment...', 'yellow');
  const localIp = detectLocalIp();
  log('   ', `Local IP: ${COLORS.green}${localIp}${COLORS.reset}`);

  const gpus = detectGpu();
  if (gpus.length > 0) {
    log('   ', `GPU(s): ${COLORS.green}${gpus.join(', ')}${COLORS.reset}`);
  } else {
    log('   ', 'GPU: none detected (software rendering only)', 'dim');
  }

  const tools = {
    bun: detectTool('bun', 'bun --version'),
    node: detectTool('node', 'node --version'),
    pm2: detectTool('pm2', 'pm2 --version'),
    nginx: detectTool('nginx', 'nginx -v 2>/dev/null'),
    docker: detectTool('docker', 'docker --version'),
    hermes: detectTool('hermes', 'hermes --version 2>/dev/null'),
    openssl: detectTool('openssl', 'openssl version'),
    nvidia: gpus.length > 0,
    hostname: detectTool('hostname', 'hostname -I'),
  };

  log('   ', 'Tools:', 'dim');
  for (const [name, found] of Object.entries(tools)) {
    const icon = found ? `${COLORS.green}✓` : `${COLORS.red}✗`;
    log('   ', `  ${icon}${COLORS.reset} ${name}${COLORS.reset}`);
  }

  // ── 2. Hermes profile check ────────────────────────────

  const existingProfiles = existsSync(PROFILES_DIR)
    ? readdirSync(PROFILES_DIR).filter(n => existsSync(`${PROFILES_DIR}/${n}/.env`))
    : [];

  const hasProfiles = existingProfiles.length > 0;
  log('   ', hasProfiles
    ? `Hermes profiles: ${COLORS.green}${existingProfiles.length} found${COLORS.reset}`
    : `Hermes profiles: ${COLORS.yellow}none yet${COLORS.reset}`);

  if (hasProfiles) {
    for (const p of existingProfiles) {
      log('   ', `  - ${p}`);
    }
  }

  // ── 3. Ask questions (only if interactive) ─────────────

  const isInteractive = process.stdin.isTTY;
  let createDefaultProfile = false;
  let corsIp = localIp;
  let corsPorts = ['3001', '3002'];
  let corsPortsDefault = ['3001', '3002'];

  if (ciMode) {
    // Non-interactive: auto-create default profile
    createDefaultProfile = true;
    corsIp = localIp;
    log('🤖', `CI mode: auto-creating default profile with detected IP ${localIp}`);
  } else if (isInteractive) {
    const ans = await ask(`Create a default profile? (Y/n)`);
    createDefaultProfile = ans.toLowerCase() !== 'n';

    const customIp = await ask(`CORS IP [${localIp}] (press Enter for auto-detected)`);
    if (customIp) corsIp = customIp;

    const customPorts = await ask(`CORS ports (comma-separated: backend,frontend) [3001,3002]`);

    if (customPorts) corsPorts = customPorts.split(',').map(p => p.trim());
  }

  // ── 4. Generate .env ───────────────────────────────────

  mkdirSync(HERMES_DIR, { recursive: true });
  mkdirSync(LOGS_DIR, { recursive: true });

  if (createDefaultProfile && !hasProfiles) {
    mkdirSync(PROFILES_DIR, { recursive: true });
    const defaultProfileDir = `${PROFILES_DIR}/default`;
    mkdirSync(defaultProfileDir, { recursive: true });
    const port = 8650;
    const apiKey = generateApiKey();
    const env = generateProfileEnv(corsIp, port, apiKey, corsPorts);
    writeFileSync(`${defaultProfileDir}/.env`, env);
    log('✅', `Created default profile at ${defaultProfileDir}/.env`, 'green');

    // Copy SOUL.md if it exists
    const soulSrc = `${ROOT}/../SOUL.md`;
    if (existsSync(soulSrc)) {
      writeFileSync(`${defaultProfileDir}/SOUL.md`, readFileSync(soulSrc, 'utf-8'));
      log('   ', '  (copied SOUL.md)');
    }
  } else if (hasProfiles) {
    log('🟢', 'Profiles already exist — skipping creation.', 'cyan');
  } else {
    log('⏭️ ', 'Skipping profile creation.', 'dim');
  }

  // ── 5. Ensure PM2 ecosystem is wired ───────────────────

  const ecoPath = `${ROOT}/../ecosystem.config.js`;
  if (existsSync(ecoPath)) {
    log('📋', `PM2 ecosystem config found at ecosystem.config.js`, 'dim');
  } else {
    log('⚠️ ', `No ecosystem.config.js found — create one or use pm2 start manually.`, 'yellow');
  }

  // ── 6. Summary ─────────────────────────────────────────

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`\n${COLORS.cyan}══════════════════════════════════════════${COLORS.reset}`);
  log('🏁', `Setup complete (${elapsed}s)`, 'green');
  console.log();

  log('📋', 'Next steps:', 'cyan');
  if (tools.pm2) {
    log('   ', `  pm2 start ecosystem.config.js`);
    log('   ', `  pm2 save`);
  }
  if (!tools.bun) {
    log('⚠️ ', 'bun is not installed. Install it: curl -fsSL https://bun.sh/install | bash', 'yellow');
  }
  if (!tools.hermes) {
    log('⚠️ ', 'hermes CLI is not installed. This is required for profiles.', 'yellow');
  }
  log('   ', `  Open http://${corsIp}:5173 in your browser`);
  console.log();

  // Wiki knowledge base (optional)
  log('📚', 'Optional — Wiki knowledge base:', 'dim');
  log('   ', '  The WikiPanel tab shows a knowledge graph built from your agent sessions.');
  log('   ', '  It requires the wiki-autopilot + wiki-transcript-ingest Hermes skills.');
  log('   ', '  To set it up:');
  log('   ', '    skill_view(name="wiki-autopilot")        # read the skill');
  log('   ', '    skill_view(name="wiki-transcript-ingest") # read the skill');
  log('   ', '    mkdir -p ~/wiki/{entities,concepts,decisions,lessons,milestones,comparisons,queries,reflections,raw/transcripts}');
  log('   ', '    cronjob schedule="0 5 * * *" prompt="Run the wiki-autopilot pipeline:');
  log('   ', '       export transcripts, score, extract, file, check index,');
  log('   ', '       audit tags, regenerate dashboard JSON."');
  console.log();
}

main().catch(err => {
  console.error(`\n${COLORS.red}✗ Setup failed:${COLORS.reset}`, err.message);
  process.exit(1);
});
